//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeBeatStreet.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int IdCart { get; set; }
        public int OrderId { get; set; }
        public int ShoeId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Shoes Shoes { get; set; }
    }
}
