//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeBeatStreet.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shoes()
        {
            this.CartTable = new HashSet<CartTable>();
            this.OrderManager = new HashSet<OrderManager>();
            this.Size = new HashSet<Size>();
        }
    
        public int IdShoes { get; set; }
        public string ShoesName { get; set; }
        public int TypeOfShoes { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public int Material { get; set; }
        public int Color { get; set; }
        public string Article { get; set; }
        public int Firm { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTable> CartTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderManager> OrderManager { get; set; }
        public virtual ShoesColor ShoesColor { get; set; }
        public virtual ShoesFirm ShoesFirm { get; set; }
        public virtual ShoesMaterial ShoesMaterial { get; set; }
        public virtual ShoesType ShoesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Size { get; set; }
    }
}
